name: Thesis SAST (AI enabled)

on:
  push:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

     

      - name: Install AI deps
        run: |
          pip install torch transformers

      - name: Run SAST scanner with AI
        run: |
          echo ">>> Running Static Scan with AI <<<"
          python thesis_sast_scannerr.py . \
            --ext ".py .php .js .html .ts" \
            --ai \
            --ai-threshold 0.56 \
            --ai-per-file 20 \
            --ai-total 250 \
            --html repo_report.html \
            --json repo_report.json

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: sast-reports
          path: |
            repo_report.html
            repo_report.json
