name: Thesis SAST (Nightly + AI)

on:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC every day
  workflow_dispatch:       # allow manual run

jobs:
  scan-ai:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies (incl. transformers/torch)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          # Ensure AI deps are present even if not in requirements.txt
          pip install "transformers>=4.41" "tokenizers" "huggingface-hub" "torch" "tqdm" || true

      - name: Run SAST scanner with AI re-ranking
        # limit AI work to keep runtime predictable
        run: |
          python thesis_sast_scannerr.py . \
            --ext .py .php .js \
            --ai --ai-threshold 0.60 --ai-per-file 10 --ai-total 200 \
            --html report_ai.html \
            --json report_ai.json

      - name: Upload AI reports
        uses: actions/upload-artifact@v4
        with:
          name: sast-ai-reports
          path: |
            report_ai.html
            report_ai.json
